services:
  downloader:
    build: .
    container_name: hf_downloader
    ports:
      - "${HF_APP_PORT}:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=${HF_HOME:-/data/huggingface}
    volumes:
      - hf_cache:${HF_CACHE:-/data/huggingface}

volumes:
  hf_cache:
